# Generated by Django 3.0.6 on 2020-06-01 22:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadDate', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='date and time of upload')),
                ('courseCode', models.CharField(max_length=10, verbose_name='assessment course code')),
                ('courseTitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='course title of assessments')),
                ('assessmentDate', models.DateField(blank=True, null=True, verbose_name='day of assessment')),
                ('description', models.TextField(blank=True, null=True, verbose_name='assessment description')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assessmentPost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content of the question')),
                ('assessment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentQuestion', to='core.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='elements/', verbose_name='Image')),
                ('assessment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentPic', to='core.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(null=True, upload_to='', verbose_name='assessment in document format')),
                ('assessment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentdoc', to='core.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answercontent', models.TextField(verbose_name='content of question')),
                ('AnswerImage', models.ImageField(blank=True, null=True, upload_to='answerImage/', verbose_name='answer image')),
                ('user', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('votes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionAnswer', to='core.Question')),
            ],
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('U', 'upvote'), ('D', 'downvote')], max_length=10)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to='core.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'answer', 'vote_type')},
            },
        ),
    ]
