# Generated by Django 3.0.6 on 2020-06-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentfile',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentimage',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.AlterUniqueTogether(
            name='uservote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='uservote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='uservote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='AssessmentFile',
        ),
        migrations.DeleteModel(
            name='AssessmentImage',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserVote',
        ),
    ]
