# Generated by Django 3.0.6 on 2020-06-03 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200602_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='s', max_length=50, verbose_name='category of service'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postText', models.TextField(verbose_name='post text')),
                ('postImage', models.ImageField(null=True, upload_to='elements/')),
                ('postby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicepost', to='core.Service')),
            ],
        ),
    ]
