# Generated by Django 3.0.6 on 2020-06-10 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_postcreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='uploadDate',
        ),
        migrations.AddField(
            model_name='service',
            name='avi',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='service',
            name='createDate',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='date and time created'),
        ),
    ]
