# Generated by Django 2.2.8 on 2020-06-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200610_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='price of item'),
        ),
    ]
