# Generated by Django 2.2.8 on 2020-07-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200703_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='PostImageWebLink',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='input image from the web'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postImage',
            field=models.ImageField(null=True, upload_to='element/'),
        ),
    ]
