# Generated by Django 2.2.8 on 2020-06-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20200608_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='facebook',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='twitter',
        ),
    ]
